# Neon PostgreSQLの接続設定
spring.datasource.url=jdbc:postgresql://ep-orange-butterfly-aekql702-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_L1qxR5PuBMDc
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernateの設定（PostgreSQL用に自動でテーブルを作る設定）
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true